version: '3.7'
services:
    socket:
        # the path of directory for build
        build: 
            context: . 
            dockerfile: Dockerfile.prod
        env_file: .env
        ports: 
            - "8000:8000"
        expose: # internal ports
            - "8000"
        environment: 
            NODE_ENV: production
            SERVER_PORT: 8000
            REDIS_HOST: "redis"
        links: 
            - "redis"
        deploy: 
            mode: global
    redis:
        image: "redis:alpine"
        expose: 
            - "6379"
        deploy: 
            replicas: 1
            # how the service should be rollback if failing updates
            rollback_config: 
                # all container rollback simultanenously
                parallelism: 0  
            update_config: 
                # number of container rollback in a single time. 
                parallelism: 1 
            restart_policy:
                condition: on-failure
                # duration required for restart attempts
                delay: 10s 
                # maximum amount of attempts
                max_attempts: 3 
            resources:
                limits:
                    # 50% of single core
                    cpus: "0.5"
                    # 50M (Megabytes) of memory
                    memory: 50M

# docker-compose up -d --no-deps --build --no-cache <service_name>